### ISSUE TITLE
does it support pypy?

### ISSUE THREAD

**Issue by ygl-rg** [fortyninemaps/karta#31]
hi, I am interested in using the lib with pypy. Does it support?

**Comment by njwilson23** [comment]
While you may be able to extract pieces that with work with PyPy, in general no, the whole package will not work. There's a lot of C and C++ code that's relied on in the dependencies (GDAL, libproj, blosc).

Finally, numpy and Cython are used quite a bit, which I think are only *sort of* compatible with PyPy right now. You might have to check and see what works.

If you're primarily using the vector types from the `karta.geometry` module, and using GeoJSON, you might have some luck, but you'll likely have to actually copy out the bits you need.

**Comment by ygl-rg** [comment]
thx. I will give it a try. I am going to use geometry & geojson module only.
