### ISSUE TITLE
Anaconda 2.7 Mac OS problem with Proj4CRS import

### ISSUE THREAD

**Issue by slazmo** [fortyninemaps/karta#41]
I seem to be having problems importing Proj4CRS within the Anaconda 2.7 enviro.   No error with import karta or the karta.crs import LonLatWGS84 - however it chokes on the Proj4CRS import (ImportError: cannot import name Proj4CRS).  There doesn't seem to be anything out there on this. I just did a full reinstall of the Anaconda 2.7 package (for Mac). I'm doing this within the Jupyter Notebook...Thx

# Load the libraries for the fetch analysis
import numpy as np
import scipy

from osgeo import gdal
import karta
from karta.crs import LonLatWGS84
#Trouble line is:
from karta.crs import Proj4CRS

**Comment by njwilson23** [comment]
What version are you using? In v0.6, `Proj4CRS` was replaced with `ProjectedCRS`, which works in more or less the same way. Unfortunately, the docs were never updated, which I just fixed in 5d0fc984d88e72a5a9bef0baee7bfd5d8fe5f741.

**Comment by slazmo** [comment]
Thanks for getting back so quickly. That did it. I really appreciate your help with this...I couldn't find any documentation. So posting on this should help others as well.
Steven

________________________________

**Comment by njwilson23** [comment]
I agree that documentation is one place that really needs more attention. It's also a great target for contributions!

I'll mark this as done, but if you find any other problems or places where docs or examples would be particularly helpful, please open an issue.

Thanks!
