### ISSUE TITLE
vtk

### ISSUE THREAD

**Issue by mlaloux** [fortyninemaps/karta#47]
In the tutorial, it is stated that

> Each geometry has appropriate methods to save data:
> mp.to_vtk("my_vtk.vtk")

But which geometry can export in vtk ? not points, lines or polygons, nor the multis
Thanks

**Comment by njwilson23** [comment]
I'm sorry, that tutorial is quite old, and VTK writers (which were never very complete) were removed in a4a9fe98d13a7b78f2b50cbf593e645cce7f3c16.

The tutorial page in the Wiki should be replaced with content from https://github.com/fortyninemaps/karta/blob/master/doc/source/tutorial.ipynb, which itself should be checked to ensure it's up-to-date.

**Comment by njwilson23** [comment]
I've updated the documentation and removed reference to vtk.
